
#热部署生效
spring.devtools.restart.enabled: true
#设置重启的目录
#spring.devtools.restart.additional-paths: src/main/java
#classpath目录下的resources文件夹内容修改不重启
#spring.devtools.restart.exclude: resources/**

server:
  port: 8081
#  address: localhost
  session:
    timeout: 120


logging:
#  config: classpath:log4j2.xml
  config: classpath:config/log4j2-${spring.profiles.active}.xml
##  file: logs/spring-boot-logging.log
#  level:
#    org.springframework:  WARN
#    com.uniledger.app:  WARN

spring:
  # 数据库访问配置
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
#    platform: mysql
 # 使用druid
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
#      time-between-eviction-runs-millis: 60000
#      # 配置一个连接在池中最小生存的时间，单位是毫秒
#      min-evictable-idle-time-millis: 300000
#      validation-query: SELECT 1 FROM DUAL
#      test-while-idle: true
#      testOnBorrow: false
#      testOnReturn: false
#      # 打开PSCache，并且指定每个连接上PSCache的大小
#      poolPreparedStatements: true
#      maxPoolPreparedStatementPerConnectionSize: 20
#      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#      filters: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#    connectionProperties:
#      druid:
#        stat:
#          mergeSql: true
#          slowSqlMillis: 5000
#    # 合并多个DruidDataSource的监控数据
#    useGlobalDataSourceStat: true

mybatis:
  config-location: classpath:config/mybatis/mybatis-config.xml
  mapperLocations: classpath:config/mybatis/mapper/*Mapper.xml
  typeAliasesPackage: com.uniledger.app.model
  checkConfigLocation: true
