
#热部署生效
spring.devtools.restart.enabled: true
#spring.devtools.restart.enabled: false
#设置重启的目录
spring.devtools.restart.additional-paths: elm-api/src/main/java
#classpath目录下的resources文件夹内容修改不重启
#spring.devtools.restart.exclude: resources/**

server:
##  address: localhost
#  session:
#    timeout: 120
#  port: 8081
  port: 8443
  ssl:
    key-store: classpath:keystore/keystore.p12
    key-store-password: uniapp
    key-store-type: PKCS12
#    key-alias: tomcat


logging:
#  config: classpath:log4j2.xml
  config: classpath:config/log4j2-${spring.profiles.active}.xml
##  file: logs/spring-boot-logging.log
#  level:
#    org.springframework:  WARN
#    com.uniledger.app:  WARN

spring:
  # 数据库访问配置
  datasource:
#    url: jdbc:mysql://www.wxcsdb88.com:3306/elm?serverTimezone=UTC&useSSL=false
    url: jdbc:mysql://localhost:3306/elm?serverTimezone=UTC&useSSL=false
    username: elm
    password: elm_123456
    driver-class-name: com.mysql.jdbc.Driver
#    platform: mysql
 # 使用druid
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
#      time-between-eviction-runs-millis: 60000
#      # 配置一个连接在池中最小生存的时间，单位是毫秒
#      min-evictable-idle-time-millis: 300000
#      validation-query: SELECT 1 FROM DUAL
#      test-while-idle: true
#      testOnBorrow: false
#      testOnReturn: false
#      # 打开PSCache，并且指定每个连接上PSCache的大小
#      poolPreparedStatements: true
#      maxPoolPreparedStatementPerConnectionSize: 20
#      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#      filters: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#    connectionProperties:
#      druid:
#        stat:
#          mergeSql: true
#          slowSqlMillis: 5000
#    # 合并多个DruidDataSource的监控数据
#    useGlobalDataSourceStat: true
  redis:
        database: 1
        #    服务器地址
      # host: 192.168.1.13
      # host: 192.168.1.14
#        host: www.wxcsdb88.com
        host: localhost
  #      host: 172.17.7.109
      #   服务器连接端口
        port: 6379
        #    链接密码
        password:
        #    链接超时时间（毫秒）
        timeout: 0
        jedis:
            pool:
              max-active: 48
              # 最大阻塞等待时间（负值表示没有限制）
              max-wait: 3000
              # 最大空闲链接
              max-idle: 8
              # 最小空闲链接
              min-idle: 0

mybatis:
  config-location: classpath:config/mybatis/mybatis-config.xml
  mapperLocations: classpath:config/mybatis/mapper/*Mapper.xml
  typeAliasesPackage: com.uniledger.app.model
  checkConfigLocation: true
