# 基础参数， 公有的

spring:
  profiles:
#    active: dev  # dev 环境
    active: test # test 环境
#    active: prod # prod 环境
  main:
    banner-mode:  console
  mvc:
    throw-exception-if-no-handler-found: true
  aop:
    auto: true
    proxy-target-class: false

  resources:
    add-mappings: false
    

#BANNER
#Banner file location.
banner:
  location: classpath:banner.txt
  charset: UTF-8

# tomcat最大线程数，默认为200
server:
  tomcat:
    max-threads:  800
    # tomcat的URI编码
    uri-encoding: UTF-8
#  port: 8443
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: uniapp
#    key-store-type: PKCS12
#    key-alias: tomcat
